### ISSUE TITLE
Is data.world useful for this project?

### ISSUE THREAD

**Issue by maxwelllincoln** [periodo/periodo-umbrella-periods#1]
I was playing around with fetching the period definitions and making some simple queries etc., and the thought of using [data.world](https://data.world) might be useful for examining *umbrellafication* 🙄 strategies. I went ahead and created a [project](https://data.world/maxwell/periodo) over there and wrote an initial naive query for aggregating period definitions by their preferred label and the associated minimum start interval and maximum end interval. The platform offers some cool interactive data query and collaboration tools that you all might find interesting.

**Comment by rybesh** [comment]
I hadn't heard of data.world before, but this looks cool! @ptgolden @atomrab 

I'm not sure that aggregating in a way that takes spatial coverage into account will be possible with a SPARQL query, but I agree that this is really useful for exploring possible strategies.
